--
--  Copyright (c) 2025, German Rivera
--
--
--  SPDX-License-Identifier: Apache-2.0
--

--
--  @summary Strongly-Typed C compiler
--
with STC_Compiler.Lexer;
with STC_Compiler.Parser;
with Ada.Characters.Handling;
with Ada.Directories;
with Ada.Exceptions;
with Ada.Strings.Fixed;

package body STC_Compiler is

   --  Derive an Ada package name from a .stc file stem (e.g. "cpu.caches" -> "Cpu.Caches").
   function To_Ada_Package_Name (Stem : String) return String with SPARK_Mode => Off is
      Result    : String := Stem;
      Cap_Next  : Boolean := True;
   begin
      for I in Result'Range loop
         if Result (I) = '.' or else Result (I) = '_' then
            Cap_Next := True;
         elsif Cap_Next then
            Result (I) := Ada.Characters.Handling.To_Upper (Result (I));
            Cap_Next := False;
         end if;
      end loop;
      return Result;
   end To_Ada_Package_Name;

   --  Write a minimal Ada package spec stub to Output_Dir so its timestamp
   --  can be compared against the source .stc file on subsequent builds.
   procedure Generate_Stub_Ada_Spec (File_Name : String; Output_Dir : String)
      with SPARK_Mode => Off
   is
      Simple   : constant String := Ada.Directories.Simple_Name (File_Name);
      --  Strip the ".stc" suffix (4 characters) to get the stem.
      Stem     : constant String := Simple (Simple'First .. Simple'Last - 4);
      Pkg_Name : constant String := To_Ada_Package_Name (Stem);
      Out_Path : constant String := Output_Dir & "/" & Stem & ".ads";
      Ada_File : Ada.Text_IO.File_Type;
   begin
      Ada.Text_IO.Create (File => Ada_File,
                          Mode => Ada.Text_IO.Out_File,
                          Name => Out_Path);
      Ada.Text_IO.Put_Line (Ada_File, "--  Generated by stcc from " & Simple);
      Ada.Text_IO.Put_Line (Ada_File, "--  (Stub: code generation not yet fully implemented)");
      Ada.Text_IO.Put_Line (Ada_File, "package " & Pkg_Name & " is");
      Ada.Text_IO.Put_Line (Ada_File, "end " & Pkg_Name & ";");
      Ada.Text_IO.Close (Ada_File);
   end Generate_Stub_Ada_Spec;

   procedure Compile_File (File_Name    : String;
                           Machine_Width : Positive := 32;
                           Output_Dir   : String := "") with SPARK_Mode => Off is
      Compiler_Obj : Compiler_Type := (others => <>);
   begin
      Log_Message ("Compiling file " & File_Name & " ...");
      Init_Compiler (Compiler_Obj, File_Name, Machine_Width);
      Parser.Parse_File (Compiler_Obj);
      Cleanup_Compiler (Compiler_Obj);
      if Output_Dir /= "" then
         Generate_Stub_Ada_Spec (File_Name, Output_Dir);
      end if;

   exception
      when E : others =>
         Ada.Text_IO.Put_Line (Ada.Text_IO.Standard_Error, Ada.Exceptions.Exception_Message (E));
         raise;
   end Compile_File;

   procedure Init_Compiler (Compiler_Obj : out Compiler_Type; File_Name : String; Machine_Width : Positive := 32) is
   begin
      Ada.Text_IO.Open (File => Compiler_Obj.File_Obj,
                        Mode => Ada.Text_IO.In_File,
                        Name => File_Name);

      Compiler_Obj.File_Name := new String'(File_Name);
      Compiler_Obj.Machine_Width := Machine_Width;
      Compiler_Obj.Initialized := True;
      Lexer.Init_Lexer (Compiler_Obj);
      Parser.Init_Parser (Compiler_Obj);
   end Init_Compiler;

   procedure Cleanup_Compiler (Compiler_Obj : in out Compiler_Type) is
   begin
      Ada.Text_IO.Close (File => Compiler_Obj.File_Obj);
      Compiler_Obj.Initialized := False;
   end Cleanup_Compiler;

   procedure Log_Message (Message : String) with SPARK_Mode => Off is
   begin
      Ada.Text_IO.Put_Line (Ada.Text_IO.Standard_Error, Message);
   end Log_Message;

   procedure Log_Compiler_Error (Compiler_Obj : Compiler_Type; Message : String) is
      use Ada.Strings.Fixed;
      Lexer_Obj : Lexer_Type renames Compiler_Obj.Lexer_Obj;
   begin
      Log_Message (Compiler_Obj.File_Name.all & ":" &
                   Trim (Lexer_Obj.Line_Number'Image, Ada.Strings.Left) & ":" &
                   Trim (Lexer_Obj.Column_Number'Image, Ada.Strings.Left) &
                   " error: " & Message);
   end Log_Compiler_Error;

   procedure Log_Compiler_Error (Compiler_Obj : Compiler_Type;
                                 Token : Token_Type;
                                 Message : String) is
      use Ada.Strings.Fixed;
   begin
      Log_Message (Compiler_Obj.File_Name.all & ":" &
                   Trim (Token.Line_Number'Image, Ada.Strings.Left) & ":" &
                   Trim (Token.Column_Number'Image, Ada.Strings.Left) &
                   " error: " & Message);
   end Log_Compiler_Error;

end STC_Compiler;